export const watchCollection = [
  {
    id: 1,
    title: "Aquarius",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 2,
    title: "Pisces",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 3,
    title: "Aries",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 4,
    title: "Taurus",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 5,
    title: "Gemini",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 6,
    title: "Cancer",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 7,
    title: "Leo",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 8,
    title: "Virgo",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 9,
    title: "Libra",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 10,
    title: "Scorpio",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 11,
    title: "Sagittarius",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
  {
    id: 12,
    title: "Capricorn",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 333,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  },
];

export const watchDetailSample = {
    id: 11,
    title: "Sagittarius",
    img: "img/watch.png",
    imgDesc: "Black strap, silver face",
    price: 33,
    company: "Aureola",
    info:
      "The only home we've ever known billions upon billions concept of the number one something incredible is waiting to be known realm of the galaxies radio telescope. Courage of our questions with pretty stories for which there's little good evidence permanence of the stars shores of the cosmic ocean star stuff harvesting star light descended from astronomers? Kindling the energy hidden in matter dream of the mind's eye the sky calls to us how far away two ghostly white figures in coveralls and helmets are softly dancing two ghostly white figures in coveralls and helmets are softly dancing and billions upon billions upon billions upon billions upon billions upon billions upon billions.",
    inCart: false,
    count: 0,
    total: 0,
  };
